source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EARestrictedScrollView-Example', :exclusive => true do
  pod 'EARestrictedScrollView', :path => '../'
end

target 'Tests', :exclusive => true do
  pod 'EARestrictedScrollView', :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
