source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'EARestrictedScrollView-Example' do
  pod 'EARestrictedScrollView', :path => '../'
end

target 'Tests' do
  pod 'EARestrictedScrollView', :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end

