name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pods
        run: pod install --project-directory=Example

      - name: Run tests
        run: set -o pipefail && xcodebuild test -workspace Example/EARestrictedScrollView-Example.xcworkspace -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.2' | xcpretty

      - name: Lint pod
        run: pod lib lint
